
exception E(x : Number, y : String) = "EEEEEE"

try 5 {
    E(x) -> print("Uh oh")
}

